// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: proto/relay.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to subscribe to events
// Exactly one of app_id, topic_id, or org_id must be provided:
// - topic_id: Subscribe to events for a specific topic
// - app_id: Subscribe to events for all topics in an application
// - org_id: Subscribe to events for all applications and topics in an organization
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID (optional, mutually exclusive with topic_id and org_id)
	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Topic ID (optional, mutually exclusive with app_id and org_id)
	// If provided, subscribes to events for this specific topic
	TopicId string `protobuf:"bytes,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	// Organization ID (optional, mutually exclusive with app_id and topic_id)
	// If provided, subscribes to events for all applications and topics in this organization
	OrgId string `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Machine ID (required) - unique identifier for the client machine
	MachineId     string `protobuf:"bytes,4,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SubscribeRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *SubscribeRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SubscribeRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

// Webhook event message
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP method
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// Full URL
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Request path
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Query parameters (JSON string)
	Query string `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	// Request headers (JSON string)
	Headers string `protobuf:"bytes,5,opt,name=headers,proto3" json:"headers,omitempty"`
	// Request body (base64 encoded)
	Body string `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	// Content type
	ContentType string `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Content length
	ContentLength string `protobuf:"bytes,8,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	// Remote address
	RemoteAddr string `protobuf:"bytes,9,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	// Timestamp (nanoseconds since epoch)
	Timestamp int64 `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Application ID
	AppId string `protobuf:"bytes,11,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Topic ID
	TopicId string `protobuf:"bytes,12,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	// Event type: "webhook" for webhook events, "disconnect" for disconnect events
	EventType     string `protobuf:"bytes,13,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Event) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Event) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Event) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Event) GetHeaders() string {
	if x != nil {
		return x.Headers
	}
	return ""
}

func (x *Event) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Event) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Event) GetContentLength() string {
	if x != nil {
		return x.ContentLength
	}
	return ""
}

func (x *Event) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Event) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

// Request to list applications
type ListApplicationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by organization ID. If not provided, returns all accessible applications
	OrgId         string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_proto_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{2}
}

func (x *ListApplicationsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// Response with list of applications
type ListApplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*Application         `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_proto_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{3}
}

func (x *ListApplicationsResponse) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

// Application message
type Application struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TopicCount    int32                  `protobuf:"varint,6,opt,name=topic_count,json=topicCount,proto3" json:"topic_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_proto_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{4}
}

func (x *Application) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Application) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Application) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Application) GetTopicCount() int32 {
	if x != nil {
		return x.TopicCount
	}
	return 0
}

// Request to list topics
type ListTopicsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: Application ID. If not provided, returns all topics across all accessible applications
	AppId         string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsRequest) Reset() {
	*x = ListTopicsRequest{}
	mi := &file_proto_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsRequest) ProtoMessage() {}

func (x *ListTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsRequest.ProtoReflect.Descriptor instead.
func (*ListTopicsRequest) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{5}
}

func (x *ListTopicsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

// Response with list of topics
type ListTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_proto_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{6}
}

func (x *ListTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

// Topic message
type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ApplicationId string                 `protobuf:"bytes,6,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_proto_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{7}
}

func (x *Topic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Topic) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Topic) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Topic) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

// Request to create an anonymous ephemeral channel
type CreateAnonymousChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnonymousChannelRequest) Reset() {
	*x = CreateAnonymousChannelRequest{}
	mi := &file_proto_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnonymousChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnonymousChannelRequest) ProtoMessage() {}

func (x *CreateAnonymousChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnonymousChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateAnonymousChannelRequest) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{8}
}

// Response with anonymous channel information
type CreateAnonymousChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	WebhookUrl    string                 `protobuf:"bytes,2,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"` // e.g. "https://ingest.hookie.sh/anon/anon_xxx"
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`   // Unix timestamp (seconds)
	Limits        *AnonymousLimits       `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnonymousChannelResponse) Reset() {
	*x = CreateAnonymousChannelResponse{}
	mi := &file_proto_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnonymousChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnonymousChannelResponse) ProtoMessage() {}

func (x *CreateAnonymousChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnonymousChannelResponse.ProtoReflect.Descriptor instead.
func (*CreateAnonymousChannelResponse) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAnonymousChannelResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *CreateAnonymousChannelResponse) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *CreateAnonymousChannelResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *CreateAnonymousChannelResponse) GetLimits() *AnonymousLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

// Anonymous channel rate limits
type AnonymousLimits struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestsPerDay    int64                  `protobuf:"varint,1,opt,name=requests_per_day,json=requestsPerDay,proto3" json:"requests_per_day,omitempty"`
	RequestsPerMinute int64                  `protobuf:"varint,2,opt,name=requests_per_minute,json=requestsPerMinute,proto3" json:"requests_per_minute,omitempty"`
	MaxPayloadBytes   int64                  `protobuf:"varint,3,opt,name=max_payload_bytes,json=maxPayloadBytes,proto3" json:"max_payload_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AnonymousLimits) Reset() {
	*x = AnonymousLimits{}
	mi := &file_proto_relay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnonymousLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnonymousLimits) ProtoMessage() {}

func (x *AnonymousLimits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnonymousLimits.ProtoReflect.Descriptor instead.
func (*AnonymousLimits) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{10}
}

func (x *AnonymousLimits) GetRequestsPerDay() int64 {
	if x != nil {
		return x.RequestsPerDay
	}
	return 0
}

func (x *AnonymousLimits) GetRequestsPerMinute() int64 {
	if x != nil {
		return x.RequestsPerMinute
	}
	return 0
}

func (x *AnonymousLimits) GetMaxPayloadBytes() int64 {
	if x != nil {
		return x.MaxPayloadBytes
	}
	return 0
}

// Message sent from client to relay during Subscribe stream
// First message must be SubscribeRequest, subsequent messages should be Ready
type SubscribeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*SubscribeMessage_Subscribe
	//	*SubscribeMessage_Ready
	Message       isSubscribeMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeMessage) Reset() {
	*x = SubscribeMessage{}
	mi := &file_proto_relay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeMessage) ProtoMessage() {}

func (x *SubscribeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeMessage.ProtoReflect.Descriptor instead.
func (*SubscribeMessage) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{11}
}

func (x *SubscribeMessage) GetMessage() isSubscribeMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SubscribeMessage) GetSubscribe() *SubscribeRequest {
	if x != nil {
		if x, ok := x.Message.(*SubscribeMessage_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *SubscribeMessage) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Message.(*SubscribeMessage_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

type isSubscribeMessage_Message interface {
	isSubscribeMessage_Message()
}

type SubscribeMessage_Subscribe struct {
	Subscribe *SubscribeRequest `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type SubscribeMessage_Ready struct {
	Ready *Ready `protobuf:"bytes,2,opt,name=ready,proto3,oneof"`
}

func (*SubscribeMessage_Subscribe) isSubscribeMessage_Message() {}

func (*SubscribeMessage_Ready) isSubscribeMessage_Message() {}

// Ready signal sent by client to indicate readiness for next event
type Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_proto_relay_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{12}
}

var File_proto_relay_proto protoreflect.FileDescriptor

const file_proto_relay_proto_rawDesc = "" +
	"\n" +
	"\x11proto/relay.proto\x12\x05relay\"z\n" +
	"\x10SubscribeRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\tR\atopicId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x04 \x01(\tR\tmachineId\"\xe3\x02\n" +
	"\x05Event\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12\x18\n" +
	"\aheaders\x18\x05 \x01(\tR\aheaders\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12!\n" +
	"\fcontent_type\x18\a \x01(\tR\vcontentType\x12%\n" +
	"\x0econtent_length\x18\b \x01(\tR\rcontentLength\x12\x1f\n" +
	"\vremote_addr\x18\t \x01(\tR\n" +
	"remoteAddr\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\x12\x15\n" +
	"\x06app_id\x18\v \x01(\tR\x05appId\x12\x19\n" +
	"\btopic_id\x18\f \x01(\tR\atopicId\x12\x1d\n" +
	"\n" +
	"event_type\x18\r \x01(\tR\teventType\"0\n" +
	"\x17ListApplicationsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"R\n" +
	"\x18ListApplicationsResponse\x126\n" +
	"\fapplications\x18\x01 \x03(\v2\x12.relay.ApplicationR\fapplications\"\xb2\x01\n" +
	"\vApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12\x1f\n" +
	"\vtopic_count\x18\x06 \x01(\x05R\n" +
	"topicCount\"*\n" +
	"\x11ListTopicsRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\":\n" +
	"\x12ListTopicsResponse\x12$\n" +
	"\x06topics\x18\x01 \x03(\v2\f.relay.TopicR\x06topics\"\xb2\x01\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12%\n" +
	"\x0eapplication_id\x18\x06 \x01(\tR\rapplicationId\"\x1f\n" +
	"\x1dCreateAnonymousChannelRequest\"\xaf\x01\n" +
	"\x1eCreateAnonymousChannelResponse\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1f\n" +
	"\vwebhook_url\x18\x02 \x01(\tR\n" +
	"webhookUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12.\n" +
	"\x06limits\x18\x04 \x01(\v2\x16.relay.AnonymousLimitsR\x06limits\"\x97\x01\n" +
	"\x0fAnonymousLimits\x12(\n" +
	"\x10requests_per_day\x18\x01 \x01(\x03R\x0erequestsPerDay\x12.\n" +
	"\x13requests_per_minute\x18\x02 \x01(\x03R\x11requestsPerMinute\x12*\n" +
	"\x11max_payload_bytes\x18\x03 \x01(\x03R\x0fmaxPayloadBytes\"|\n" +
	"\x10SubscribeMessage\x127\n" +
	"\tsubscribe\x18\x01 \x01(\v2\x17.relay.SubscribeRequestH\x00R\tsubscribe\x12$\n" +
	"\x05ready\x18\x02 \x01(\v2\f.relay.ReadyH\x00R\x05readyB\t\n" +
	"\amessage\"\a\n" +
	"\x05Ready2\xc5\x02\n" +
	"\fRelayService\x126\n" +
	"\tSubscribe\x12\x17.relay.SubscribeMessage\x1a\f.relay.Event(\x010\x01\x12S\n" +
	"\x10ListApplications\x12\x1e.relay.ListApplicationsRequest\x1a\x1f.relay.ListApplicationsResponse\x12A\n" +
	"\n" +
	"ListTopics\x12\x18.relay.ListTopicsRequest\x1a\x19.relay.ListTopicsResponse\x12e\n" +
	"\x16CreateAnonymousChannel\x12$.relay.CreateAnonymousChannelRequest\x1a%.relay.CreateAnonymousChannelResponseB%Z#github.com/hookie-sh/hookie/backend/relay/proto;protob\x06proto3"

var (
	file_proto_relay_proto_rawDescOnce sync.Once
	file_proto_relay_proto_rawDescData []byte
)

func file_proto_relay_proto_rawDescGZIP() []byte {
	file_proto_relay_proto_rawDescOnce.Do(func() {
		file_proto_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_relay_proto_rawDesc), len(file_proto_relay_proto_rawDesc)))
	})
	return file_proto_relay_proto_rawDescData
}

var file_proto_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_relay_proto_goTypes = []any{
	(*SubscribeRequest)(nil),               // 0: relay.SubscribeRequest
	(*Event)(nil),                          // 1: relay.Event
	(*ListApplicationsRequest)(nil),        // 2: relay.ListApplicationsRequest
	(*ListApplicationsResponse)(nil),       // 3: relay.ListApplicationsResponse
	(*Application)(nil),                    // 4: relay.Application
	(*ListTopicsRequest)(nil),              // 5: relay.ListTopicsRequest
	(*ListTopicsResponse)(nil),             // 6: relay.ListTopicsResponse
	(*Topic)(nil),                          // 7: relay.Topic
	(*CreateAnonymousChannelRequest)(nil),  // 8: relay.CreateAnonymousChannelRequest
	(*CreateAnonymousChannelResponse)(nil), // 9: relay.CreateAnonymousChannelResponse
	(*AnonymousLimits)(nil),                // 10: relay.AnonymousLimits
	(*SubscribeMessage)(nil),               // 11: relay.SubscribeMessage
	(*Ready)(nil),                          // 12: relay.Ready
}
var file_proto_relay_proto_depIdxs = []int32{
	4,  // 0: relay.ListApplicationsResponse.applications:type_name -> relay.Application
	7,  // 1: relay.ListTopicsResponse.topics:type_name -> relay.Topic
	10, // 2: relay.CreateAnonymousChannelResponse.limits:type_name -> relay.AnonymousLimits
	0,  // 3: relay.SubscribeMessage.subscribe:type_name -> relay.SubscribeRequest
	12, // 4: relay.SubscribeMessage.ready:type_name -> relay.Ready
	11, // 5: relay.RelayService.Subscribe:input_type -> relay.SubscribeMessage
	2,  // 6: relay.RelayService.ListApplications:input_type -> relay.ListApplicationsRequest
	5,  // 7: relay.RelayService.ListTopics:input_type -> relay.ListTopicsRequest
	8,  // 8: relay.RelayService.CreateAnonymousChannel:input_type -> relay.CreateAnonymousChannelRequest
	1,  // 9: relay.RelayService.Subscribe:output_type -> relay.Event
	3,  // 10: relay.RelayService.ListApplications:output_type -> relay.ListApplicationsResponse
	6,  // 11: relay.RelayService.ListTopics:output_type -> relay.ListTopicsResponse
	9,  // 12: relay.RelayService.CreateAnonymousChannel:output_type -> relay.CreateAnonymousChannelResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_relay_proto_init() }
func file_proto_relay_proto_init() {
	if File_proto_relay_proto != nil {
		return
	}
	file_proto_relay_proto_msgTypes[11].OneofWrappers = []any{
		(*SubscribeMessage_Subscribe)(nil),
		(*SubscribeMessage_Ready)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_relay_proto_rawDesc), len(file_proto_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_relay_proto_goTypes,
		DependencyIndexes: file_proto_relay_proto_depIdxs,
		MessageInfos:      file_proto_relay_proto_msgTypes,
	}.Build()
	File_proto_relay_proto = out.File
	file_proto_relay_proto_goTypes = nil
	file_proto_relay_proto_depIdxs = nil
}
